-- Add explicit INSERT policy for risk_alerts table
-- Risk alerts are system-generated by monitor-assets edge function using service role
-- This makes the security intention explicit

CREATE POLICY "Service role can insert risk alerts"
ON public.risk_alerts FOR INSERT
WITH CHECK (auth.role() = 'service_role');